version: "3"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/node/app
    ports:
      - "3333:3333"
      - "8080:8080"
    depends_on:
      - mariadb
  mariadb:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: todolist
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8891:80"
    links:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306

