version: "3"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules
      - adonis_volume:/data
    ports:
      - "3333:3333"
    depends_on:
      - mariadb
  mariadb:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: todolist
    volumes:
      - mariadb_volume:/data
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8891:80"
    links:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306

volumes:
  mariadb_volume:
  adonis_volume:
  pma_volumes:
